#?? ????? ?? ??
file:
  directory: D:\LHC\download\quadruaple

#???? ?? ???
const:
  default-page-size: 10

#?????? ??
spring:
  application:
    name: quadruaple

    config:
      import: "classpath:application-secret.yml"

  #File ??? ??
  servlet:
    multipart:
      max-file-size: 50MB

constant:
  info-const:
    title: JWT Practice
    description: JWT + Security ???
    version: v0.1
  jwt-const:
    issuer: green@green.kr #?? ???
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-key: Authorization
    claim-key: signedUser
    bearer-format: JWT
    schema: Bearer
    access-token-expiry: 86_400_000 #1? (ms) 60 * 60 * 24 * 1000
    refresh-token-expiry: 1_296_000_000 #15? (ms)60 * 60 * 24 * 15 * 1000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1_296_000 #15? (ms)


#MyBatis ??
mybatis:
  mapper-locations: mappers/**/*.xml

#Swagger ??
springdoc:
  swagger-ui:
    default-models-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true