spring:
  #데이터베이스 연결 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/quadruaple
    username: root
    password: green502

  #구글 이메일 설정(SMTP) - 인증 문자 날리는 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: quadrupleart@gmail.com
    password: mnistucxsknhsaen
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true